### PR TITLE
fix: provide json tags for InitOptions struct

### PR DESCRIPTION
**Pull request by meinenec**
allows users to set init options like `BackendConfigs` as `backend-configs` in their .vela.yml

### CODE REVIEW

**Review by davidvader — APPROVED** [review]

**Comment by meinenec** [comment]
I can add a `nolint:lll,maligned` to the struct if we would like to suppress these.
I hesitated to add it since this PR doesn't actually do anything that affects those checks. I just touched the struct to add labels.

**Comment by jbrockopp** [comment]
@meinenec thoughts on doing a hybrid approach of what you suggested above?

Thinking you could add the `nolint: maligned` to the top of the `InitOptions{}` struct to address that issue?

But for the `lll` issues, could we just updated the comments to be multi-line?

I'll provide an example below to make sure I'm clear:

This is what we have currently for one of the fields:

```go
		// Copy the contents of the given module into the target directory before initialization. "-from-module=SOURCE"
		FromModule string `json:"from-module,omitempty"`
```

I'm thinking we could change that to:

```go
		// Copy the contents of the given module into the target
		// directory before initialization. "-from-module=SOURCE"
		FromModule string `json:"from-module,omitempty"`
```

**Comment by meinenec** [comment]
@jbrockopp I'm alright with that as well, thanks.

**Review by wass3r — CHANGES_REQUESTED** [review]
I think we want to use `two_words` instead of `two-words`, ie. underscores (`_`) vs dashes (`-`). We started using the convention here:
- https://github.com/go-vela/vela-docker/blob/master/cmd/vela-docker/daemon.go#L33
- https://github.com/go-vela/vela-docker/blob/master/cmd/vela-docker/daemon.go#L37

In JSON it's also a bit easier to address, ie. `hello.json.two_words` vs `hello.json['two-words']`, although there is no strict standard. CamelCase and snake_case are most commonly used. Since we already went down the `_` path elsewhere, I propose sticking to that.

**Comment by meinenec** [comment]
@wass3r would that require users to pass these parameters with an underscore in their .vela.yml?
for example, `backend_configs` instead of `backend-configs`

I think we wanted to keep the parameters as close to the [terraform CLI](https://www.terraform.io/docs/cli/commands/init.html) as we could. I don't think this makes it too different, but I'm curious what your thoughts are.

**Comment by meinenec** [comment]
@wass3r looks like our docs expected underscore to work so I'll make that change 🙂

**Review by wass3r — APPROVED** [review]

**Review by jbrockopp — APPROVED** [review]
LGTM

**Pull request merged**
